#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only.
# See the file usr/src/LICENSING.NOTICE in this distribution or
# http://www.opensolaris.org/license/ for details.
#
# ident	"@(#)Makefile	1.1	04/09/28 SMI"
#

# To enable apptrace, comment out the next line
DISABLE_APPTRACE=   $(POUND_SIGN)

include ../Makefile.targ
include $(SRC)/lib/Makefile.lib
include $(SRC)/lib/Makefile.lib.64
include $(SRC)/lib/Makefile.spec

$(DISABLE_APPTRACE)install: $(ROOTABILIB64)
