#! /bin/sh

SUDO="setuid root"
if [ ! -f $HOME/bin/setuid ]; then
	SUDO=sudo
fi

sync ; sync
if [ -e /dev/dtrace ]; then
	echo rmmod dtracedrv
	$SUDO rmmod dtracedrv
	#sleep 1
	sync ; sync
fi

echo "Loading: dtracedrv.ko"
$SUDO insmod dtracedrv.ko
sleep 1
$SUDO chmod 666 /dev/dtrace
$SUDO chmod 666 /dev/fbt

echo "Preparing symbols..."
for s in \
	kallsyms		\
	get_symbol_offset	\
	modules		        \
	__symbol_get		\
	sys_call_table		\
	kern_addr_valid		\
	hrtimer_init		\
	hrtimer_start		\
	hrtimer_cancel
do
	grep " $s" /proc/kallsyms >/dev/fbt
done

echo "Probes available:"
dtrace -l | wc -l 
