#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only.
# See the file usr/src/LICENSING.NOTICE in this distribution or
# http://www.opensolaris.org/license/ for details.
#
#ident	"@(#)Makefile.targ	1.1	03/09/02 SMI"

.KEEP_STATE:

LIBRARY	= libdtrace.a
VERS	= .1
OBJECTS	= dtrace.o
