#! /bin/sh
#
# 'warn' colorises gcc warnings and errors which is useful during
# the lets-get-it-together phase when there is so many errors which
# swamp the output.

# make-me Q=0
warn=warn
if [ ! -f /home/fox/bin/warn ]; then
	warn=
fi
finished=no
while [ $finished = "no" ]
do
	case $1 in
	  -*) flags="$flags $1"
		shift
		;;
	  *)
		finished=yes
		;;
	esac
done

if [ `uname -m` != x86_64 ]; then

  	export PTR32=-D_ILP32
	export BUILD_i386=1
fi

build_dir=/lib/modules/`uname -r`/build
if [ ! -d $build_dir ]; then
	build_dir=/usr/src/linux/
fi
exec $warn make $flags -C $build_dir M=`pwd` $@
