#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only.
# See the file usr/src/LICENSING.NOTICE in this distribution or
# http://www.opensolaris.org/license/ for details.
#
# ident	"@(#)Makefile	1.4	04/01/28 SMI"
#

include ../Makefile.com
include ../../Makefile.lib.64

CPPFLAGS += -D_SYSCALL32

install: all $(ROOTLIBS64) $(ROOTLINKS64)
