#! /usr/bin/perl
# simple script for testing dtrace -c:
# dtrace -n 'syscall:::/pid==$target/{printf("%d",pid);}' -c utils/doit2
print "This is doit2 -- PID $$\n";
$| = 1;
my $x = 0;
while (1) {
        print ".";
        if ($x++ > 50) {
                $x = 0;
                print "\n";
        }
#       for (my $i = 0; $i < 100; $i++) {
#               mkdir("/");
#       }
	open(FH, "/etc/hosts");
        sleep(1);
}
