#! /usr/bin/perl

# $Header:$

# Handle syscall names which vary in location and available from
# one kernel and archicture to the next.

# Author: Paul Fox
# Date: June 2008

use strict;
use warnings;

use File::Basename;
use FileHandle;
use Getopt::Long;
use IO::File;
use POSIX;

#######################################################################
#   Command line switches.					      #
#######################################################################
my %opts;

sub main
{
	Getopt::Long::Configure('no_ignore_case');
	usage() unless GetOptions(\%opts,
		'help',
		);

	usage() if ($opts{help});
	my $ver = `uname -r`;
	chomp($ver);

	my %calls;
	foreach my $f (glob("/lib/modules/$ver/build/include/asm/unistd*")) {
		print "Processing: $f\n";
		my $fh = new FileHandle($f);
		if (!$fh) {
			print "Cannot open -- $!\n";
			next;
		}
		while (<$fh>) {
			next if !/define\s+(__NR[A-Z_a-z0-9]+)\s+(.*)/;
			$calls{$1} = $2;
		}
	}

	my $name = $ARGV[0];
	my $fh = new FileHandle(">drivers/dtrace/syscalls-$name.tbl");
	print $fh "/* This file is automatically generated from mksyscall.pl */\n";
	print $fh "/* Do not edit! */\n";
	foreach my $c (sort(keys(%calls))) {
		print $fh "#if defined($c)\n";
		print $fh " [$c] = \"$c\",\n";
		print $fh "#endif\n";
	}

}
#######################################################################
#   Print out command line usage.				      #
#######################################################################
sub usage
{
	print "Some help...\n";
	print "Usage: \n";
	print "\n";
	print "Switches:\n";
	print "\n";
	exit(1);
}

main();
0;

